### ISSUE TITLE
Daijisen or 研究社 新和英大辞典第５版 import issue.

### ISSUE THREAD

**Issue by mjuzikfrik** [FooSoft/yomichan-import#1]
Hello,

It's great that made importing epwing dictionaries possible into Yomichan. Daijirin imports fine but when I try to do so with above mentioned ones I get an error "failed to find compatible extractor for '大辞'" in case of Daijisen or "failed to find compatible extractor for '研究社　新和英大辞典　第５版'" for the latter.

How you can resolve the issue.

**Comment by FooSoft** [comment]
Yeah, as listed in `README.md`, 大辞林 is the only supported EPWING dictionary in the first release. This is because I have to go and write regular expressions for every single dictionary that Yomichan is to support... 大辞泉 and 新和英大辞典 are next on my list of dictionaries to add support to.

**Comment by FooSoft** [comment]
Support was added in the latest release
