### ISSUE TITLE
Request: Add 英辞郎 (Eijiro) parser

### ISSUE THREAD

**Issue by sukerokushin** [FooSoft/yomichan-import#20]
This might be a lot of work because Eijiro is huge, but it's a very powerful dictionary for translation (which is what I mostly use Yomichan for). I don't have any experience to help you out here, but I do have it in its text format.

**Comment by kfdz277** [comment]
here's where you can buy the text version of ver.144.8 (I still don't know how I can get this converted into EPWING)
https://booth.pm/ja/items/777563

**Comment by sukerokushin** [comment]
(requesting deletion)
