### ISSUE TITLE
Conversion process failed: exit status 1

### ISSUE THREAD

**Issue by oussama-he** [FooSoft/yomichan-import#22]
I would like to convert an epwing Japanese dictionary using Yomichan import, but I get this error:
`conversion process failed: exit status 1`

![Screenshot at 2020-03-26 17-15-28](https://user-images.githubusercontent.com/18425315/77669930-cda99d00-6f85-11ea-9194-1c7ca9d29a42.png)

This is the structure of the folder:

![Screenshot at 2020-03-26 17-15-51](https://user-images.githubusercontent.com/18425315/77669958-d4381480-6f85-11ea-9920-e3fcff62c776.png)

**Comment by FooSoft** [comment]
Probably fixed with new version.
