### ISSUE TITLE
Request: Support for German EPWING dictionary

### ISSUE THREAD

**Issue by glokta1** [FooSoft/yomichan-import#25]
Hey,
As the title states, I'm trying to get Yomichan to work with a German EPWING dictionary. It'd be really cool if you could start expanding EPWING support to non-Japanese dictionaries starting with the German one. I know at least a dozen people who could benefit from this. 

German EPWING dictionary: https://mega.nz/file/4RJB2CSa#qT1Tlpkd9zaLkMcX03HVUmdY3cvNGb9bQMFDjz6HK7M

**Comment by FooSoft** [comment]
Yomichan is Japanese-language specific, and cannot support other languages, sorry.
