### ISSUE TITLE
What is the purpose of each element in a dictionary entry

### ISSUE THREAD

**Issue by Noah-Barsky** [FooSoft/yomichan-import#42]
For an example entry like this
```json
[
        "休学",
        "きゅうがく",
        "",
        "",
        0,
        [
            "きゅうがく【休学】\ntemporary absence from school.～する have\u003ca term's\u003eleave of absence from school.\n"
        ],
        54840,
        ""
],
```

I can gather the first two elements are the word, the sixth is definitions, and the seventh is the id.
But what are the third, fourth, fifth, and eighth for?
If someone could enlighten me on this, I would be grateful.

**Comment by Thermospore** [comment]
see here for a description: https://github.com/FooSoft/yomichan/tree/master/ext/data/schemas
