### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by mjuzikfrik** [FooSoft/yomichan-import#9]
Hello,

I'm trying to convert any of the supported dictionaries but to no avail. Here's the screenshot. 

![image](https://user-images.githubusercontent.com/16630872/29239347-dfa91516-7f4c-11e7-9379-75b2b5c72e53.png)

**Comment by FooSoft** [comment]
@mjuzikfrik when the console application window for ZeroEPWING opens up, are you allowing it to finish executing?

**Comment by mjuzikfrik** [comment]
Well, nothing opens. I get the error immediately after clicking on the import button.

**Comment by FooSoft** [comment]
Did you extract `yomichan-import` from the archive along with all of the other files first, or are you just running the application from the ZIP file directly?

**Comment by mjuzikfrik** [comment]
I have extracted all the files as they are.

**Comment by FooSoft** [comment]
I'm betting that this is due to ASCII only text support in the libeb used by ZeroEPWING (basically the ￥ directory separators are causing problems for the old library). I have an idea for a workaround that I'll try to implement this weekend.

**Comment by FooSoft** [comment]
Probably fixed with new version.
